# Project information
site_name: My MkDocs Project
site_description: 'An example MkDocs project using the Material theme'
site_url: 'https://marc-jr.github.io/mk-docs'  # Changed to lowercase

# Theme settings
theme:
  name: material  # Changed to match the description

# Navbar settings (site structure)
nav:
  - Home: index.md
  - About: about.md
  - Multipass: multipass.md  # Capitalized for consistency

# Extra settings
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

# Repository configuration (for the edit link on pages)
repo_name: marc-jr/mk-docs  # Changed to lowercase
repo_url: https://github.com/marc-jr/mk-docs  # Changed to lowercase
edit_uri: edit/main/docs/
